spring.application.name=inkspire

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=inkspire
spring.data.mongodb.username=asuna
spring.data.mongodb.password=m

